import type {
  FranchiseReceipt,
  MemoEntry,
  ReceiptKpi,
} from "@/features/franchise-receipts/types";
import { RECEIPT_STATUS_META } from "@/features/franchise-receipts/types";

function toIsoDate(dotted: string): string {
  return dotted.replaceAll(".", "-");
}

function getLocalIsoDate(date = new Date()): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

interface RawReceipt {
  id: number;
  date: string;
  channel: FranchiseReceipt["channel"];
  bizType: FranchiseReceipt["bizType"];
  name: string;
  owner: string;
  phone: string;
  salesRep: string;
  csRep: string | null;
  status: FranchiseReceipt["status"];
  stage: number;
  due: string;
  memo: string;
  isMine: boolean;
  unassigned: boolean;
}

const RAW_RECEIPTS: RawReceipt[] = [
  {
    id: 1,
    date: "2026.07.13",
    channel: "직접 영업",
    bizType: "개인 사업자",
    name: "카페 아모르",
    owner: "김아름",
    phone: "010-2231-8842",
    salesRep: "-",
    csRep: null,
    status: "wait",
    stage: 1,
    due: "07.15",
    memo: "서류 미제출, 안내 발송 완료",
    isMine: false,
    unassigned: true,
  },
  {
    id: 2,
    date: "2026.07.13",
    channel: "전환",
    bizType: "법인 사업자",
    name: "소녀코리아마스터링",
    owner: "박소연",
    phone: "010-4471-2093",
    salesRep: "이도현",
    csRep: "서지은",
    status: "docMissing",
    stage: 1,
    due: "07.14",
    memo: "사업자등록증 재제출 요청",
    isMine: true,
    unassigned: false,
  },
  {
    id: 3,
    date: "2026.07.12",
    channel: "토스리드건",
    bizType: "개인 사업자",
    name: "삼겹담 신정점",
    owner: "최우진",
    phone: "010-9987-1120",
    salesRep: "장은주",
    csRep: "최혜민",
    status: "review",
    stage: 2,
    due: "07.16",
    memo: "심사팀 확인 중",
    isMine: false,
    unassigned: false,
  },
  {
    id: 4,
    date: "2026.07.12",
    channel: "명변",
    bizType: "법인 사업자",
    name: "대국민푸드",
    owner: "윤석민",
    phone: "010-3345-7781",
    salesRep: "장은주",
    csRep: "최혜민",
    status: "techWait",
    stage: 3,
    due: "07.13",
    memo: "기술지원팀 배정 대기",
    isMine: true,
    unassigned: false,
  },
  {
    id: 5,
    date: "2026.07.11",
    channel: "직접 영업",
    bizType: "개인 사업자",
    name: "행복한 카페",
    owner: "정하늘",
    phone: "010-5521-3344",
    salesRep: "이도현",
    csRep: "서지은",
    status: "done",
    stage: 4,
    due: "07.11",
    memo: "설치 완료, 만족도 조사 예정",
    isMine: true,
    unassigned: false,
  },
  {
    id: 6,
    date: "2026.07.11",
    channel: "전환",
    bizType: "법인 사업자",
    name: "명동떡볶이 본점",
    owner: "강수아",
    phone: "010-6612-9087",
    salesRep: "-",
    csRep: null,
    status: "wait",
    stage: 0,
    due: "07.17",
    memo: "",
    isMine: false,
    unassigned: true,
  },
  {
    id: 7,
    date: "2026.07.11",
    channel: "토스리드건",
    bizType: "개인 사업자",
    name: "브런치 온더코너",
    owner: "서예린",
    phone: "010-7789-4432",
    salesRep: "장은주",
    csRep: "최혜민",
    status: "docWait",
    stage: 1,
    due: "07.14",
    memo: "고객 서류 제출 대기",
    isMine: false,
    unassigned: false,
  },
  {
    id: 8,
    date: "2026.07.10",
    channel: "직접 영업",
    bizType: "법인 사업자",
    name: "미라클버거 강남점",
    owner: "문재현",
    phone: "010-2298-6612",
    salesRep: "이도현",
    csRep: "서지은",
    status: "techDone",
    stage: 2,
    due: "07.15",
    memo: "VAN사 계약 확인 필요",
    isMine: true,
    unassigned: false,
  },
  {
    id: 9,
    date: "2026.07.10",
    channel: "명변",
    bizType: "개인 사업자",
    name: "황금올리브 분식",
    owner: "임도윤",
    phone: "010-8834-2201",
    salesRep: "-",
    csRep: null,
    status: "docMissing",
    stage: 1,
    due: "07.12",
    memo: "대표자 신분증 미제출",
    isMine: false,
    unassigned: true,
  },
  {
    id: 10,
    date: "2026.07.09",
    channel: "전환",
    bizType: "법인 사업자",
    name: "스시나가야 판교점",
    owner: "배지훈",
    phone: "010-1123-9945",
    salesRep: "장은주",
    csRep: "최혜민",
    status: "tossDone",
    stage: 4,
    due: "07.10",
    memo: "설치 기사 배정 완료",
    isMine: false,
    unassigned: false,
  },
  {
    id: 11,
    date: "2026.07.09",
    channel: "토스리드건",
    bizType: "개인 사업자",
    name: "커피스탠드 온",
    owner: "노유진",
    phone: "010-4456-7723",
    salesRep: "이도현",
    csRep: "서지은",
    status: "review",
    stage: 2,
    due: "07.13",
    memo: "",
    isMine: true,
    unassigned: false,
  },
  {
    id: 12,
    date: "2026.07.08",
    channel: "직접 영업",
    bizType: "법인 사업자",
    name: "왕가마솥순대국",
    owner: "조민석",
    phone: "010-3321-6654",
    salesRep: "-",
    csRep: null,
    status: "wait",
    stage: 0,
    due: "07.18",
    memo: "접수 확인 대기",
    isMine: false,
    unassigned: true,
  },
  {
    id: 13,
    date: "2026.07.08",
    channel: "명변",
    bizType: "개인 사업자",
    name: "초록마을 청과",
    owner: "한소희",
    phone: "010-9912-3345",
    salesRep: "장은주",
    csRep: "서지은",
    status: "techWait",
    stage: 3,
    due: "07.11",
    memo: "기술지원 이관 서류 준비",
    isMine: false,
    unassigned: false,
  },
  {
    id: 14,
    date: "2026.07.07",
    channel: "전환",
    bizType: "법인 사업자",
    name: "델리샵 프레시",
    owner: "오세훈",
    phone: "010-6678-1102",
    salesRep: "이도현",
    csRep: "최혜민",
    status: "done",
    stage: 4,
    due: "07.07",
    memo: "최종 완료",
    isMine: false,
    unassigned: false,
  },
  {
    id: 15,
    date: "2026.07.07",
    channel: "직접 영업",
    bizType: "개인 사업자",
    name: "라뜰리에 베이커리",
    owner: "심유나",
    phone: "010-2287-5541",
    salesRep: "-",
    csRep: null,
    status: "docMissing",
    stage: 1,
    due: "07.09",
    memo: "통장사본 재요청",
    isMine: false,
    unassigned: true,
  },
  {
    id: 16,
    date: "2026.07.06",
    channel: "토스리드건",
    bizType: "법인 사업자",
    name: "제일곱창 본점",
    owner: "백승호",
    phone: "010-4432-8871",
    salesRep: "장은주",
    csRep: "서지은",
    status: "rejected",
    stage: 1,
    due: "07.06",
    memo: "가맹 취소 요청",
    isMine: true,
    unassigned: false,
  },
  {
    id: 17,
    date: "2026.07.06",
    channel: "명변",
    bizType: "개인 사업자",
    name: "모모산도 이태원점",
    owner: "류지호",
    phone: "010-7723-4409",
    salesRep: "이도현",
    csRep: "최혜민",
    status: "review",
    stage: 2,
    due: "07.12",
    memo: "",
    isMine: false,
    unassigned: false,
  },
  {
    id: 18,
    date: "2026.07.05",
    channel: "전환",
    bizType: "법인 사업자",
    name: "그린테이블 샐러드",
    owner: "남기범",
    phone: "010-1198-2276",
    salesRep: "-",
    csRep: null,
    status: "wait",
    stage: 0,
    due: "07.19",
    memo: "",
    isMine: false,
    unassigned: true,
  },
];

function createMemoHistory(r: RawReceipt): MemoEntry[] {
  const receiptDate = r.date.replaceAll("-", ".");
  const entries: MemoEntry[] = [
    {
      id: `${r.id}-seed-registered`,
      meta: `${receiptDate} 09:00:00 · 시스템`,
      content: "가맹 접수가 등록되었습니다.",
      pinned: false,
    },
  ];
  if (r.memo) {
    entries.push({
      id: `${r.id}-seed-memo`,
      meta: `${receiptDate} 14:20:00 · 담당 CS`,
      content: r.memo,
      pinned: false,
    });
  }
  entries.push({
    id: `${r.id}-seed-status`,
    meta: `${receiptDate} 09:10:00 · 시스템`,
    content: `현재 상태: ${RECEIPT_STATUS_META[r.status].label}`,
    pinned: false,
  });
  return entries;
}

export function createInitialReceipts(): FranchiseReceipt[] {
  const today = getLocalIsoDate();
  return RAW_RECEIPTS.map((r) => ({
    id: r.id,
    receiptDate: [1, 2, 5].includes(r.id) ? today : toIsoDate(r.date),
    channel: r.channel,
    bizType: r.bizType,
    name: r.name,
    owner: r.owner,
    phone: r.phone,
    bizNo: "000-00-00000",
    salesRep: r.salesRep === "-" ? "토스 연동" : r.salesRep,
    csRep: r.csRep,
    internet: r.id % 3 === 0 ? "3S" : null,
    status: r.status,
    stage: r.stage,
    due: r.due,
    memo: r.memo,
    memoHistory: createMemoHistory(r),
    isMine: r.isMine,
    unassigned: r.unassigned,
  }));
}

export const RECEIPT_KPIS: ReceiptKpi[] = [
  { key: "today", label: "오늘 접수", value: 12 },
  { key: "docWait", label: "서류 대기", value: 8 },
  { key: "docMissing", label: "서류 미비", value: 4 },
  { key: "review", label: "심사 대기", value: 15 },
  { key: "doneToday", label: "오늘 완료", value: 9 },
];
