import type { InstallRecord } from "@/features/installations/types";

function withOperationDefaults(record: InstallRecord): InstallRecord {
  const merged = {
    requestMemo: record.symptom || record.memo,
    planMemo: "",
    plannedDevices: [],
    deviceResults: [],
    attachments: [],
    completionPhotoMissingReason: "",
    resultMemo: "",
    completedAt: null,
    storeWorkHistory: [],
    ...record,
  };

  return {
    ...merged,
    notiHistory: merged.notiHistory.map((entry) => ({ ...entry })),
    plannedDevices: merged.plannedDevices.map((device) => ({
      ...device,
    })),
    deviceResults: merged.deviceResults.map((device) => ({
      ...device,
    })),
    attachments: merged.attachments.map((attachment) => ({
      ...attachment,
    })),
    storeWorkHistory: merged.storeWorkHistory.map((entry) => ({
      ...entry,
    })),
  };
}

const SEED_INSTALLS: InstallRecord[] = [
  {
    id: 1,
    kind: "install",
    customerName: "카페 아모르",
    phone: "010-2231-8842",
    address: "서울 성동구 성수동2가 12-3",
    addressDetail: "1층",
    product: "카드단말기 A100",
    status: "productReady",
    assignedTech: "박기사",
    trackingNo: null,
    scheduledDate: "2026-07-18",
    timeSlot: "오전(10~13시)",
    symptom: "",
    registeredBy: "가맹 접수 연동",
    registeredAt: "2026-07-16T10:20:00+09:00",
    source: "franchise",
    memo: "매장 오픈일 전 설치 희망",
    requestMemo: "매장 오픈일 전 설치 희망. 카운터 우측 전원 위치 확인 필요",
    planMemo: "오픈 전날 오전 방문 우선",
    plannedDevices: [
      {
        id: "plan-1-a100",
        modelName: "카드단말기 A100",
        serialNo: "A100-2407-001",
        quantity: 1,
        status: "stock",
        currentLocation: "본사 재고",
        memo: "초기 설치 예정",
      },
    ],
    attachments: [
      {
        id: "att-1-blueprint",
        type: "blueprint",
        fileName: "카페아모르_카운터도면.pdf",
        uploadedAt: "2026-07-16T10:25:00+09:00",
      },
    ],
    notiHistory: [{ id: "n1", label: "2026.07.16 10:22 · 접수 안내 발송" }],
  },
  {
    id: 2,
    kind: "install",
    customerName: "삼겹담 신정점",
    phone: "010-9987-1120",
    address: "서울 양천구 신정동 456-7",
    addressDetail: "2층 201호",
    product: "카드단말기 A100 + 프린터",
    status: "scheduled",
    assignedTech: "이기사",
    trackingNo: null,
    scheduledDate: "2026-07-17",
    timeSlot: "오후(14~17시)",
    symptom: "",
    registeredBy: "가맹 접수 연동",
    registeredAt: "2026-07-15T16:40:00+09:00",
    source: "franchise",
    memo: "",
    planMemo: "단말기와 프린터 동시 설치",
    plannedDevices: [
      {
        id: "plan-2-a100",
        modelName: "카드단말기 A100",
        serialNo: "A100-2407-014",
        quantity: 1,
        status: "assignedToTech",
        currentLocation: "이기사",
        memo: "",
      },
      {
        id: "plan-2-printer",
        modelName: "영수증 프린터 P20",
        serialNo: "P20-2406-033",
        quantity: 1,
        status: "stock",
        currentLocation: "본사 재고",
        memo: "",
      },
    ],
    notiHistory: [
      { id: "n2", label: "2026.07.15 16:41 · 접수 안내 발송" },
      { id: "n3", label: "2026.07.16 09:05 · 일정 확정 안내 발송" },
    ],
  },
  {
    id: 3,
    kind: "install",
    customerName: "오후의 커피",
    phone: "010-2567-9031",
    address: "서울 마포구 연남동 89-1",
    addressDetail: "",
    product: "카드단말기 A100",
    status: "moving",
    assignedTech: "박기사",
    trackingNo: null,
    scheduledDate: "2026-07-16",
    timeSlot: "오전(10~13시)",
    symptom: "",
    registeredBy: "가맹 접수 연동",
    registeredAt: "2026-07-14T11:00:00+09:00",
    source: "franchise",
    memo: "",
    notiHistory: [
      { id: "n4", label: "2026.07.14 11:02 · 접수 안내 발송" },
      { id: "n5", label: "2026.07.16 08:50 · 기사 배정 안내 발송" },
    ],
  },
  {
    id: 4,
    kind: "install",
    customerName: "명동떡볶이 본점",
    phone: "010-4471-2093",
    address: "서울 중구 명동2가 33-1",
    addressDetail: "지하 1층",
    product: "카드단말기 A100",
    status: "installDone",
    assignedTech: "최기사",
    trackingNo: null,
    scheduledDate: "2026-07-14",
    timeSlot: "오후(14~17시)",
    symptom: "",
    registeredBy: "서지은",
    registeredAt: "2026-07-12T09:30:00+09:00",
    source: "manual",
    memo: "",
    resultMemo: "설치 완료. 서명 확인 후 사진 등록",
    completedAt: "2026-07-14T15:20:00+09:00",
    deviceResults: [
      {
        id: "result-4-a100",
        modelName: "카드단말기 A100",
        serialNo: "A100-2407-009",
        action: "installed",
        memo: "카운터 설치",
      },
    ],
    attachments: [
      {
        id: "att-4-photo",
        type: "completionPhoto",
        fileName: "명동떡볶이_완료사진.jpg",
        uploadedAt: "2026-07-14T15:18:00+09:00",
      },
    ],
    storeWorkHistory: [
      {
        id: "history-4",
        label: "2026.07.14 · 설치 완료 · 카드단말기 A100",
      },
    ],
    notiHistory: [
      { id: "n6", label: "2026.07.14 15:20 · 설치 완료 안내 발송" },
    ],
  },
  {
    id: 5,
    kind: "install",
    customerName: "브릭 하우스 강남점",
    phone: "010-7788-2231",
    address: "서울 강남구 논현동 55-2",
    addressDetail: "3층",
    product: "카드단말기 A100",
    status: "receipt",
    assignedTech: null,
    trackingNo: null,
    scheduledDate: null,
    timeSlot: null,
    symptom: "",
    registeredBy: "가맹 접수 연동",
    registeredAt: "2026-07-16T09:15:00+09:00",
    source: "franchise",
    memo: "",
    notiHistory: [],
  },
  {
    id: 6,
    kind: "parcel",
    customerName: "성수 베이커리",
    phone: "010-3281-0472",
    address: "서울 성동구 성수이로 3",
    addressDetail: "302호",
    product: "카드단말기 A100",
    status: "shipping",
    assignedTech: null,
    trackingNo: "CJ 6829471003",
    scheduledDate: null,
    timeSlot: null,
    symptom: "",
    registeredBy: "가맹 접수 연동",
    registeredAt: "2026-07-15T14:10:00+09:00",
    source: "franchise",
    memo: "",
    notiHistory: [
      { id: "n7", label: "2026.07.15 18:00 · 배송 시작 안내 발송" },
    ],
  },
  {
    id: 7,
    kind: "parcel",
    customerName: "포레스트 키친",
    phone: "010-6940-1185",
    address: "서울 종로구 계동길 21",
    addressDetail: "",
    product: "프린터 단품",
    status: "received",
    assignedTech: null,
    trackingNo: "한진 4471820933",
    scheduledDate: null,
    timeSlot: null,
    symptom: "",
    registeredBy: "최혜민",
    registeredAt: "2026-07-13T10:00:00+09:00",
    source: "manual",
    memo: "",
    notiHistory: [
      { id: "n8", label: "2026.07.14 15:30 · 수령 확인 안내 발송" },
    ],
  },
  {
    id: 8,
    kind: "parcel",
    customerName: "소녀코리아마스터링",
    phone: "010-4471-2093",
    address: "서울 마포구 서교동 12-9",
    addressDetail: "4층",
    product: "카드단말기 A100",
    status: "productReady",
    assignedTech: null,
    trackingNo: null,
    scheduledDate: null,
    timeSlot: null,
    symptom: "",
    registeredBy: "가맹 접수 연동",
    registeredAt: "2026-07-16T08:30:00+09:00",
    source: "franchise",
    memo: "",
    notiHistory: [],
  },
  {
    id: 9,
    kind: "parcel",
    customerName: "행복한 카페",
    phone: "010-8842-3177",
    address: "서울 노원구 상계동 77-3",
    addressDetail: "",
    product: "프린터 단품",
    status: "receipt",
    assignedTech: null,
    trackingNo: null,
    scheduledDate: null,
    timeSlot: null,
    symptom: "",
    registeredBy: "한지민",
    registeredAt: "2026-07-16T11:05:00+09:00",
    source: "manual",
    memo: "재발송 요청 건",
    notiHistory: [],
  },
  {
    id: 10,
    kind: "as",
    customerName: "브릭 하우스",
    phone: "010-8442-3177",
    address: "서울 강남구 논현동 33-5",
    addressDetail: "1층",
    product: "카드단말기 A100",
    status: "receipt",
    assignedTech: null,
    trackingNo: null,
    scheduledDate: null,
    timeSlot: null,
    symptom: "용지 걸림, 인쇄가 안 됨",
    registeredBy: "한지민",
    registeredAt: "2026-07-16T08:55:00+09:00",
    source: "manual",
    memo: "",
    notiHistory: [],
  },
  {
    id: 11,
    kind: "as",
    customerName: "하루분식",
    phone: "010-7103-5529",
    address: "서울 은평구 응암동 12-9",
    addressDetail: "",
    product: "프린터 단품",
    status: "asDone",
    assignedTech: "이기사",
    trackingNo: null,
    scheduledDate: "2026-07-14",
    timeSlot: "오후(14~17시)",
    symptom: "단말기 전원 불량",
    registeredBy: "서지은",
    registeredAt: "2026-07-13T13:20:00+09:00",
    source: "manual",
    memo: "",
    notiHistory: [
      { id: "n9", label: "2026.07.14 16:40 · 수리 완료 안내 발송" },
    ],
  },
  {
    id: 12,
    kind: "as",
    customerName: "대국민푸드",
    phone: "010-9982-4410",
    address: "서울 송파구 잠실동 8-1",
    addressDetail: "8층",
    product: "카드단말기 A100",
    status: "checking",
    assignedTech: "최기사",
    trackingNo: null,
    scheduledDate: null,
    timeSlot: null,
    symptom: "결제 승인 지연",
    registeredBy: "최혜민",
    registeredAt: "2026-07-15T17:00:00+09:00",
    source: "manual",
    memo: "부품 재고 확인 중",
    notiHistory: [],
  },
];

export function createInitialInstalls(): InstallRecord[] {
  return SEED_INSTALLS.map(withOperationDefaults);
}
