import {
  CalendarCheckIcon,
  CalendarClockIcon,
  CheckCircle2Icon,
  ClipboardListIcon,
  FileWarningIcon,
  WifiIcon,
} from "lucide-react";
import { CS_REPRESENTATIVES } from "@/lib/cs-representatives";
import type {
  ManagementKind,
  PageConfig,
} from "@/features/management-preview/types";

const reps = [...CS_REPRESENTATIVES];

export const configs: Record<ManagementKind, PageConfig> = {
  changes: {
    title: "변경 관리",
    description: "가맹점 정보 변경 접수와 서류 진행 상태를 관리합니다.",
    createLabel: "변경 접수 등록",
    searchPlaceholder: "상호명, 대표자명, 연락처, 사업자번호 통합 검색",
    kpis: [
      { label: "오늘 접수", value: "8", icon: ClipboardListIcon, tone: "blue" },
      {
        label: "서류 대기",
        value: "14",
        icon: CalendarClockIcon,
        tone: "amber",
      },
      { label: "서류 미비", value: "5", icon: FileWarningIcon, tone: "red" },
      {
        label: "접수 완료",
        value: "32",
        icon: CheckCircle2Icon,
        tone: "green",
      },
    ],
    tabs: ["전체", "내 업무", "서류대기", "서류미비", "접수완료"],
    tabField: "status",
    filters: [
      {
        key: "changeType",
        label: "변경유형 전체",
        options: [
          "변경유형 전체",
          "통장변경",
          "상호변경",
          "대표자 변경",
          "주소변경",
          "업종변경",
        ],
      },
      {
        key: "bizType",
        label: "사업자유형 전체",
        options: ["사업자유형 전체", "개인사업자", "법인사업자"],
      },
      { key: "paid", label: "입금 전체", options: ["입금 전체", "Y", "N"] },
      {
        key: "receivedAt",
        label: "접수일 기간",
        type: "dateRange",
      },
    ],
    columns: [
      {
        key: "receivedAt",
        label: "접수일",
        initialWidth: 110,
        minWidth: 96,
        sortType: "date",
      },
      {
        key: "changeType",
        label: "변경유형",
        initialWidth: 110,
        minWidth: 90,
        sortType: "text",
      },
      {
        key: "bizType",
        label: "사업자유형",
        initialWidth: 120,
        minWidth: 100,
        sortType: "text",
      },
      {
        key: "name",
        label: "상호명",
        kind: "identity",
        initialWidth: 180,
        minWidth: 130,
        sortType: "text",
      },
      { key: "owner", label: "대표자", initialWidth: 90, minWidth: 72 },
      { key: "phone", label: "연락처", initialWidth: 140, minWidth: 120 },
      {
        key: "registeredBy",
        label: "등록자",
        initialWidth: 100,
        minWidth: 84,
        sortType: "text",
      },
      {
        key: "manager",
        label: "담당자",
        initialWidth: 100,
        minWidth: 88,
        sortType: "text",
      },
      {
        key: "paid",
        label: "입금여부",
        initialWidth: 90,
        minWidth: 74,
        sortType: "text",
      },
      {
        key: "status",
        label: "상태",
        kind: "badge",
        initialWidth: 110,
        minWidth: 96,
        sortType: "status",
      },
      {
        key: "memoCount",
        label: "메모",
        kind: "memo",
        initialWidth: 64,
        minWidth: 64,
        resizable: false,
      },
    ],
    inlineEditKeys: [
      "receivedAt",
      "changeType",
      "bizType",
      "status",
      "paid",
      "manager",
    ],
    inlineFields: [
      {
        key: "status",
        label: "상태",
        type: "select",
        options: ["서류대기", "서류미비", "접수완료"],
      },
    ],
    sections: [
      {
        title: "변경 정보",
        fields: [
          {
            key: "changeType",
            label: "변경유형",
            type: "select",
            options: [
              "통장변경",
              "상호변경",
              "대표자 변경",
              "주소변경",
              "업종변경",
            ],
          },
          {
            key: "receivedAt",
            label: "접수날짜",
            type: "date",
          },
          { key: "manager", label: "담당자", type: "select", options: reps },
          {
            key: "paid",
            label: "입금 여부",
            type: "select",
            options: ["N", "Y"],
          },
        ],
      },
      {
        title: "사업자 정보",
        fields: [
          {
            key: "bizType",
            label: "사업자 유형",
            type: "select",
            options: ["개인사업자", "법인사업자"],
          },
          { key: "name", label: "상호명" },
          { key: "owner", label: "대표자명" },
          {
            key: "phone",
            label: "연락처",
            placeholder: "010-0000-0000",
          },
          {
            key: "bizNo",
            label: "사업자번호",
            placeholder: "000-00-00000",
          },
        ],
      },
    ],
    rows: [
      {
        id: "C-260716-08",
        receivedAt: "2026.07.16",
        changeType: "대표자 변경",
        name: "성수 베이커리",
        bizNo: "212-18-•••••",
        owner: "김도윤",
        phone: "010-3281-0472",
        bizType: "개인사업자",
        status: "서류미비",
        paid: "N",
        registeredBy: "서지은",
        manager: "서지은",
        memoCount: "3",
      },
      {
        id: "C-260716-07",
        receivedAt: "2026.07.16",
        changeType: "통장변경",
        name: "포레스트 키친",
        bizNo: "107-21-•••••",
        owner: "이서연",
        phone: "010-6940-1185",
        bizType: "법인사업자",
        status: "서류대기",
        paid: "Y",
        registeredBy: "서지은",
        manager: "최혜민",
        memoCount: "1",
      },
      {
        id: "C-260715-12",
        receivedAt: "2026.07.15",
        changeType: "상호변경",
        name: "오후의 커피",
        bizNo: "410-09-•••••",
        owner: "박현우",
        phone: "010-2567-9031",
        bizType: "개인사업자",
        status: "접수완료",
        paid: "Y",
        registeredBy: "최혜민",
        manager: "최혜민",
        memoCount: "2",
      },
      {
        id: "C-260715-10",
        receivedAt: "2026.07.15",
        changeType: "주소변경",
        name: "브릭 하우스",
        bizNo: "129-86-•••••",
        owner: "정유진",
        phone: "010-8442-3177",
        bizType: "법인사업자",
        status: "서류대기",
        paid: "N",
        registeredBy: "서지은",
        manager: "미배정",
        memoCount: "0",
      },
      {
        id: "C-260714-05",
        receivedAt: "2026.07.14",
        changeType: "업종변경",
        name: "하루분식",
        bizNo: "505-12-•••••",
        owner: "오민석",
        phone: "010-7103-5529",
        bizType: "개인사업자",
        status: "접수완료",
        paid: "Y",
        registeredBy: "서지은",
        manager: "서지은",
        memoCount: "4",
      },
    ],
  },
  woo: {
    title: "우국상 관리",
    description:
      "우국상 접수와 인터넷·카드가맹 진행 현황을 한곳에서 관리합니다.",
    createLabel: "우국상 접수 등록",
    searchPlaceholder: "상호명, 대표자명, 연락처, 사업자번호, 주소 통합 검색",
    kpis: [
      { label: "오늘 접수", value: "5", icon: ClipboardListIcon, tone: "blue" },
      {
        label: "7일 내 오픈",
        value: "9",
        icon: CalendarCheckIcon,
        tone: "amber",
      },
      { label: "가맹 미확인", value: "7", icon: FileWarningIcon, tone: "red" },
      {
        label: "가맹 완료",
        value: "24",
        icon: CheckCircle2Icon,
        tone: "green",
      },
    ],
    tabs: ["전체", "내 업무", "신규", "명의변경", "승계"],
    tabField: "category",
    filters: [
      {
        key: "merchantStatus",
        label: "가맹 여부 전체",
        options: ["가맹 여부 전체", "가맹완료", "가맹미확인"],
      },
      {
        key: "setting",
        label: "세팅 전체",
        options: ["세팅 전체", "PC세팅", "포스세팅"],
      },
      {
        key: "simplePay",
        label: "간편결제 전체",
        options: [
          "간편결제 전체",
          "토스페이",
          "카카오페이",
          "제로페이",
          "미등록",
        ],
      },
      {
        key: "receivedAt",
        label: "접수일 기간",
        type: "dateRange",
      },
    ],
    columns: [
      {
        key: "category",
        label: "분류",
        initialWidth: 100,
        minWidth: 80,
        sortType: "text",
      },
      {
        key: "receivedAt",
        label: "접수일",
        initialWidth: 110,
        minWidth: 96,
        sortType: "date",
      },
      {
        key: "openDate",
        label: "오픈일",
        initialWidth: 110,
        minWidth: 96,
        sortType: "date",
      },
      {
        key: "name",
        label: "상호명",
        kind: "identity",
        initialWidth: 170,
        minWidth: 130,
        sortType: "text",
      },
      { key: "owner", label: "대표자", initialWidth: 90, minWidth: 72 },
      { key: "phone", label: "연락처", initialWidth: 140, minWidth: 120 },
      {
        key: "registeredBy",
        label: "등록자",
        initialWidth: 100,
        minWidth: 86,
        sortType: "text",
      },
      {
        key: "manager",
        label: "담당자",
        initialWidth: 100,
        minWidth: 88,
        sortType: "text",
      },
      {
        key: "merchantStatus",
        label: "가맹여부",
        initialWidth: 110,
        minWidth: 96,
        sortType: "text",
      },
      {
        key: "setting",
        label: "세팅",
        initialWidth: 90,
        minWidth: 76,
        sortType: "text",
      },
      {
        key: "simplePay",
        label: "간편결제",
        initialWidth: 100,
        minWidth: 88,
        sortType: "text",
      },
      {
        key: "memoCount",
        label: "메모",
        kind: "memo",
        initialWidth: 64,
        minWidth: 64,
        resizable: false,
      },
    ],
    inlineEditKeys: [
      "receivedAt",
      "category",
      "openDate",
      "internet",
      "merchantStatus",
      "setting",
      "simplePay",
      "manager",
    ],
    sections: [
      {
        title: "접수 정보",
        fields: [
          {
            key: "category",
            label: "분류",
            type: "select",
            options: ["명의변경", "승계", "신규"],
          },
          {
            key: "receivedAt",
            label: "접수날짜",
            type: "date",
          },
          { key: "manager", label: "담당자", type: "select", options: reps },
          { key: "openDate", label: "오픈예정일", type: "date" },
        ],
      },
      {
        title: "사업자 정보",
        fields: [
          { key: "name", label: "상호명" },
          { key: "owner", label: "대표자명" },
          { key: "bizNo", label: "사업자번호" },
          {
            key: "phone",
            label: "연락처",
            placeholder: "010-4444-0357 / 010-8048-0904(매장)",
            format: "raw",
          },
          { key: "address", label: "주소", width: "wide" },
          { key: "addressDetail", label: "상세주소", width: "wide" },
        ],
      },
      {
        title: "인터넷 정보",
        fields: [
          {
            key: "internet",
            label: "인터넷",
            type: "select",
            options: ["미정", "3S", "백메가"],
          },
          {
            key: "internetOpenDate",
            label: "인터넷 개통일자",
            type: "dateText",
            placeholder: "날짜 또는 메모",
          },
        ],
      },
      {
        title: "카드 및 POS",
        fields: [
          { key: "cardReceivedAt", label: "카드가맹 접수일자", type: "date" },
          {
            key: "merchantStatus",
            label: "가맹여부",
            type: "select",
            options: ["가맹완료", "가맹미확인"],
          },
          {
            key: "setting",
            label: "세팅",
            type: "select",
            options: ["PC세팅", "포스세팅"],
          },
          {
            key: "simplePay",
            label: "간편결제",
            placeholder: "간편결제 입력",
          },
          { key: "posInstallDate", label: "포스 설치일", type: "dateText" },
          { key: "van", label: "VAN", placeholder: "직접 입력" },
          {
            key: "posProgram",
            label: "포스프로그램",
            placeholder: "직접 입력",
          },
        ],
      },
    ],
    rows: [
      {
        id: "W-260716-05",
        receivedAt: "2026.07.16",
        category: "신규",
        name: "담소 한식당",
        bizNo: "312-09-•••••",
        owner: "윤하진",
        phone: "010-9021-3475",
        openDate: "2026.07.24",
        internet: "3S",
        merchantStatus: "가맹미확인",
        registeredBy: "서지은",
        manager: "서지은",
        setting: "PC세팅",
        simplePay: "토스페이",
        memoCount: "3",
      },
      {
        id: "W-260716-04",
        receivedAt: "2026.07.16",
        category: "승계",
        name: "카페 무이",
        bizNo: "118-14-•••••",
        owner: "강민지",
        phone: "010-6634-2108",
        openDate: "2026.07.19",
        internet: "백메가",
        merchantStatus: "가맹완료",
        registeredBy: "서지은",
        manager: "최혜민",
        setting: "포스세팅",
        simplePay: "카카오페이",
        memoCount: "2",
      },
      {
        id: "W-260715-11",
        receivedAt: "2026.07.15",
        category: "명의변경",
        name: "소담족발 마포점",
        bizNo: "214-27-•••••",
        owner: "조성훈",
        phone: "010-4418-7300",
        openDate: "2026.08.01",
        internet: "미정",
        merchantStatus: "가맹미확인",
        registeredBy: "최혜민",
        manager: "미배정",
        setting: "PC세팅",
        simplePay: "미등록",
        memoCount: "1",
      },
      {
        id: "W-260714-08",
        receivedAt: "2026.07.14",
        category: "신규",
        name: "모먼트 펍",
        bizNo: "601-05-•••••",
        owner: "신예린",
        phone: "010-2270-6184",
        openDate: "2026.07.21",
        internet: "3S",
        merchantStatus: "가맹완료",
        registeredBy: "서지은",
        manager: "최혜민",
        setting: "포스세팅",
        simplePay: "제로페이",
        memoCount: "4",
      },
      {
        id: "W-260713-03",
        receivedAt: "2026.07.13",
        category: "승계",
        name: "남산 도시락",
        bizNo: "410-22-•••••",
        owner: "임재호",
        phone: "010-7951-0463",
        openDate: "2026.07.28",
        internet: "백메가",
        merchantStatus: "가맹미확인",
        registeredBy: "서지은",
        manager: "서지은",
        setting: "PC세팅",
        simplePay: "미등록",
        memoCount: "2",
      },
    ],
  },
  internet: {
    title: "인터넷 관리",
    description: "인터넷 가입 접수부터 개통, 요금과 사은품 정보를 관리합니다.",
    createLabel: "인터넷 접수 등록",
    searchPlaceholder: "상호명, 대표자명, 연락처 통합 검색",
    kpis: [
      { label: "오늘 접수", value: "6", icon: ClipboardListIcon, tone: "blue" },
      {
        label: "개통 대기",
        value: "18",
        icon: CalendarClockIcon,
        tone: "amber",
      },
      { label: "오늘 개통", value: "4", icon: WifiIcon, tone: "green" },
      {
        label: "이번 달 개통",
        value: "41",
        icon: CheckCircle2Icon,
        tone: "green",
      },
    ],
    tabs: ["전체", "접수완료", "개통완료"],
    tabField: "status",
    filters: [
      {
        key: "category",
        label: "구분 전체",
        options: ["구분 전체", "3S", "백메가"],
      },
      {
        key: "carrier",
        label: "통신사 전체",
        options: ["통신사 전체", "SKT", "KT", "LG"],
      },
      {
        key: "speed",
        label: "속도 전체",
        options: ["속도 전체", "100M", "500M", "직접입력"],
      },
      {
        key: "appliedAt",
        label: "접수일 기간",
        type: "dateRange",
      },
    ],
    columns: [
      {
        key: "appliedAt",
        label: "접수일",
        initialWidth: 110,
        minWidth: 96,
        sortType: "date",
      },
      {
        key: "openedAt",
        label: "개통완료일",
        initialWidth: 110,
        minWidth: 96,
        sortType: "date",
      },
      {
        key: "name",
        label: "상호명",
        kind: "identity",
        initialWidth: 170,
        minWidth: 130,
        sortType: "text",
      },
      { key: "owner", label: "대표자", initialWidth: 90, minWidth: 72 },
      { key: "phone", label: "연락처", initialWidth: 140, minWidth: 120 },
      {
        key: "registeredBy",
        label: "등록자",
        initialWidth: 100,
        minWidth: 86,
        sortType: "text",
      },
      {
        key: "manager",
        label: "담당자",
        initialWidth: 100,
        minWidth: 88,
        sortType: "text",
      },
      {
        key: "status",
        label: "상태",
        kind: "badge",
        initialWidth: 100,
        minWidth: 92,
        sortType: "status",
      },
      {
        key: "memoCount",
        label: "메모",
        kind: "memo",
        initialWidth: 64,
        minWidth: 64,
        resizable: false,
      },
    ],
    inlineEditKeys: [
      "appliedAt",
      "openedAt",
      "status",
      "category",
      "carrier",
      "speed",
      "monthlyFee",
    ],
    sections: [
      {
        title: "고객 정보",
        fields: [
          { key: "name", label: "상호명" },
          { key: "owner", label: "대표자명" },
          { key: "phone", label: "연락처" },
          {
            key: "region",
            label: "지역",
            type: "select",
            options: [
              "미정",
              "서울",
              "인천",
              "경기",
              "부산",
              "대전",
              "대구",
              "광주",
            ],
          },
        ],
      },
      {
        title: "접수 및 개통",
        fields: [
          {
            key: "appliedAt",
            label: "접수신청일",
            type: "date",
          },
          {
            key: "status",
            label: "상태",
            type: "select",
            options: ["접수완료", "개통완료"],
          },
          { key: "openedAt", label: "개통완료일", type: "date" },
          {
            key: "category",
            label: "구분",
            type: "select",
            options: ["3S", "백메가"],
          },
          {
            key: "carrier",
            label: "통신사",
            type: "select",
            options: ["SKT", "KT", "LG"],
          },
          {
            key: "speed",
            label: "속도",
            type: "select",
            options: ["100M", "500M", "직접입력"],
          },
        ],
      },
      {
        title: "상품 및 비용",
        fields: [
          {
            key: "extraProduct",
            label: "추가 가입상품",
            placeholder: "예: TV + 와이파이",
          },
          { key: "gift", label: "사은품", placeholder: "예: 현금 300,000원" },
          {
            key: "monthlyFee",
            label: "월요금",
            type: "money",
            placeholder: "0",
          },
          {
            key: "installFee",
            label: "설치비",
            type: "money",
            placeholder: "0",
          },
        ],
      },
    ],
    rows: [
      {
        id: "I-260716-06",
        appliedAt: "2026.07.16",
        name: "성수 베이커리",
        region: "서울",
        owner: "김도윤",
        phone: "010-3281-0472",
        category: "3S",
        carrier: "KT",
        speed: "500M",
        status: "접수완료",
        openedAt: "-",
        monthlyFee: "38,500",
        registeredBy: "서지은",
        manager: "서지은",
        memoCount: "2",
      },
      {
        id: "I-260716-05",
        appliedAt: "2026.07.16",
        name: "담소 한식당",
        region: "인천",
        owner: "윤하진",
        phone: "010-9021-3475",
        category: "백메가",
        carrier: "SKT",
        speed: "100M",
        status: "개통완료",
        openedAt: "2026.07.16",
        monthlyFee: "22,000",
        registeredBy: "서지은",
        manager: "최혜민",
        memoCount: "3",
      },
      {
        id: "I-260715-14",
        appliedAt: "2026.07.15",
        name: "카페 무이",
        region: "경기",
        owner: "강민지",
        phone: "010-6634-2108",
        category: "3S",
        carrier: "LG",
        speed: "500M",
        status: "접수완료",
        openedAt: "-",
        monthlyFee: "33,000",
        registeredBy: "최혜민",
        manager: "미배정",
        memoCount: "1",
      },
      {
        id: "I-260715-09",
        appliedAt: "2026.07.15",
        name: "브릭 하우스",
        region: "서울",
        owner: "정유진",
        phone: "010-8442-3177",
        category: "백메가",
        carrier: "KT",
        speed: "직접입력",
        status: "개통완료",
        openedAt: "2026.07.15",
        monthlyFee: "44,000",
        registeredBy: "서지은",
        manager: "최혜민",
        memoCount: "4",
      },
      {
        id: "I-260714-08",
        appliedAt: "2026.07.14",
        name: "하루분식",
        region: "대전",
        owner: "오민석",
        phone: "010-7103-5529",
        category: "3S",
        carrier: "SKT",
        speed: "100M",
        status: "접수완료",
        openedAt: "-",
        monthlyFee: "19,800",
        registeredBy: "서지은",
        manager: "서지은",
        memoCount: "0",
      },
    ],
  },
};
