import type { EmployeeRecord } from "@/features/employees/types";

/** 초기 계정 공통 비밀번호. mock 전용 데모 값이며 실제 배포 전 백엔드 인증으로 교체된다. */
const DEFAULT_PASSWORD = "1234";

/** 초기 직원 계정. 실제 조직도 성격의 데이터라 데모 고객 데이터와 달리 비우지 않는다. */
export function createInitialEmployees(): EmployeeRecord[] {
  return [
    {
      id: "admin",
      username: "admin",
      password: DEFAULT_PASSWORD,
      name: "관리자",
      team: "운영관리",
      role: "admin",
      positions: [],
      active: true,
    },
    {
      id: "master",
      username: "master",
      password: DEFAULT_PASSWORD,
      name: "김마스터",
      team: "운영관리",
      role: "viewer",
      positions: ["master"],
      active: true,
    },
    {
      id: "cs-manager",
      username: "cs-manager",
      password: DEFAULT_PASSWORD,
      name: "정지은 매니저",
      team: "CS팀",
      role: "cs",
      positions: ["cs_manager"],
      active: true,
    },
    {
      id: "cs-responsible",
      username: "cs-responsible",
      password: DEFAULT_PASSWORD,
      name: "서지은 책임매니저",
      team: "CS팀",
      role: "cs",
      positions: ["cs_responsible"],
      active: true,
    },
    {
      id: "cs-lead",
      username: "cs-lead",
      password: DEFAULT_PASSWORD,
      name: "한소라 팀장",
      team: "CS팀",
      role: "cs",
      positions: ["team_lead"],
      active: true,
    },
    {
      id: "tech-manager",
      username: "tech-manager",
      password: DEFAULT_PASSWORD,
      name: "박기사 매니저",
      team: "기술지원팀",
      role: "tech",
      positions: ["tech_manager"],
      active: true,
    },
    {
      id: "tech-responsible",
      username: "tech-responsible",
      password: DEFAULT_PASSWORD,
      name: "이기사 책임매니저",
      team: "기술지원팀",
      role: "tech",
      positions: ["tech_responsible"],
      active: true,
    },
    {
      id: "tech-lead",
      username: "tech-lead",
      password: DEFAULT_PASSWORD,
      name: "최기사 팀장",
      team: "기술지원팀",
      role: "tech",
      positions: ["team_lead"],
      active: true,
    },
    {
      id: "viewer",
      username: "viewer",
      password: DEFAULT_PASSWORD,
      name: "조회 전용",
      team: "감사",
      role: "viewer",
      positions: [],
      active: true,
    },
  ];
}
